### ISSUE TITLE
Use this to record and play opus audios?

### ISSUE THREAD

**Issue by fzyzcjy** [EPNW/opus_dart#7]
Hi thanks for this wonderful library! I wonder whether we can use this to record opus audios and play opus audios?

**Comment by EPNW** [comment]
No, it is really just the audio codec. dart itself does not know the conecept of recording or playing audio, since it is hardware agnostic, so this is not possible through dart. You would encode/decode an opus audio stream on the fly and pass it to the native audio api of your respective platform.

**Comment by fzyzcjy** [comment]
Thank you!
